import { useState } from "react";
import { useSQLite, DailyReview } from "@/hooks/useSQLite";
import { useOllama } from "@/hooks/useOllama";
import {
  buildDeepSeekCBTMessages,
  parseDeepSeekResponse,
  DEEPSEEK_MODEL_NAME,
} from "@/utils/deepseekCBT";
import { Button } from "@/components/ui/button";
import {
  Brain,
  Sparkles,
  ChevronDown,
  ChevronUp,
  Loader2,
  Calendar,
  AlertCircle,
  FileText,
  Lightbulb,
} from "lucide-react";

export default function WeeklyCBTReport() {
  const { get7DayWeeklyAggregation, updateWeeklyCbtReport } = useSQLite();
  const { chat, isConnected, availableModels } = useOllama();

  const [isGenerating, setIsGenerating] = useState(false);
  const [reportMarkdown, setReportMarkdown] = useState<string>("");
  const [reasoning, setReasoning] = useState<string>("");
  const [showCoT, setShowCoT] = useState<boolean>(false);
  const [reviewsAnalyzed, setReviewsAnalyzed] = useState<DailyReview[]>([]);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    setError(null);
    setReasoning("");
    setReportMarkdown("");

    try {
      // Fetch 7-day review data from SQLite
      const { reviews, formattedLogSummary } = await get7DayWeeklyAggregation();
      setReviewsAnalyzed(reviews);

      if (reviews.length === 0) {
        setError("No daily reviews found in the database. Please submit at least one daily reflection first.");
        setIsGenerating(false);
        return;
      }

      const targetModel =
        availableModels.find(
          (m) => m === DEEPSEEK_MODEL_NAME || m.includes("deepseek") || m.includes("r1")
        ) || DEEPSEEK_MODEL_NAME;

      const messages = buildDeepSeekCBTMessages(formattedLogSummary);

      // Low-level call to Ollama targeting DeepSeek-R1 (no JSON grammar format constraint)
      const rawResponse = await chat({
        model: targetModel,
        messages,
        temperature: 0.6,
      });

      const parsed = parseDeepSeekResponse(rawResponse);
      setReasoning(parsed.reasoning);
      setReportMarkdown(parsed.report);

      // Save report into SQLite for the latest review entry
      if (reviews[0]?.review_date) {
        await updateWeeklyCbtReport(reviews[0].review_date, parsed.report);
      }
    } catch (err) {
      console.error("DeepSeek-R1 CBT report generation error:", err);
      setError(
        err instanceof Error ? err.message : "Failed to generate weekly CBT report via DeepSeek-R1."
      );
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="bg-card border border-border rounded-xl p-6 shadow-sm space-y-6">
      {/* Card Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Brain className="size-5 text-primary" />
            <h2 className="text-xl font-bold tracking-tight text-foreground">
              Weekly CBT Psychological Coaching Report
            </h2>
          </div>
          <p className="text-sm text-muted-foreground">
            Clinical CBT cognitive reframing generated by DeepSeek-R1 ({DEEPSEEK_MODEL_NAME}).
          </p>
        </div>

        <Button
          onClick={handleGenerateReport}
          disabled={isGenerating || !isConnected}
          className="gap-2 font-semibold"
        >
          {isGenerating ? (
            <>
              <Loader2 className="size-4 animate-spin text-primary-light" />
              Reasoning via DeepSeek-R1...
            </>
          ) : (
            <>
              <Sparkles className="size-4 text-amber-400" />
              Generate 7-Day CBT Analysis
            </>
          )}
        </Button>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="flex items-center gap-2 text-xs font-medium text-amber-400 bg-amber-500/10 border border-amber-500/20 p-3.5 rounded-lg">
          <AlertCircle className="size-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Collapsible Chain-of-Thought (<think> reasoning) Section */}
      {reasoning && (
        <div className="border border-indigo-500/30 bg-indigo-950/20 rounded-lg overflow-hidden">
          <button
            onClick={() => setShowCoT(!showCoT)}
            className="w-full px-4 py-3 bg-indigo-950/40 hover:bg-indigo-950/60 flex items-center justify-between text-xs font-semibold text-indigo-300 transition-colors"
          >
            <div className="flex items-center gap-2">
              <Lightbulb className="size-4 text-amber-400 animate-pulse" />
              <span>DeepSeek-R1 Internal Chain-of-Thought Reasoning (&lt;think&gt;)</span>
            </div>
            {showCoT ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}
          </button>

          {showCoT && (
            <div className="p-4 bg-black/40 text-xs font-mono text-indigo-200/90 whitespace-pre-wrap leading-relaxed border-t border-indigo-500/20 max-h-60 overflow-y-auto">
              {reasoning}
            </div>
          )}
        </div>
      )}

      {/* Generated Report Output */}
      {reportMarkdown ? (
        <div className="space-y-4">
          <div className="flex items-center justify-between text-xs text-muted-foreground border-b border-border/50 pb-2">
            <span className="flex items-center gap-1.5 font-medium">
              <Calendar className="size-3.5 text-primary" />
              Analyzed {reviewsAnalyzed.length} nightly reviews
            </span>
            <span className="flex items-center gap-1 text-emerald-400 font-semibold">
              <FileText className="size-3.5" /> Saved to SQLite
            </span>
          </div>

          <div className="prose prose-invert max-w-none text-sm leading-relaxed space-y-3 bg-secondary/30 border border-border/60 p-6 rounded-xl">
            {reportMarkdown.split("\n").map((line, idx) => {
              if (line.startsWith("# ")) {
                return (
                  <h1 key={idx} className="text-xl font-bold text-foreground pt-2">
                    {line.replace("# ", "")}
                  </h1>
                );
              }
              if (line.startsWith("## ")) {
                return (
                  <h2 key={idx} className="text-lg font-semibold text-primary pt-3 border-b border-border/40 pb-1">
                    {line.replace("## ", "")}
                  </h2>
                );
              }
              if (line.startsWith("### ")) {
                return (
                  <h3 key={idx} className="text-base font-medium text-accent-app pt-2">
                    {line.replace("### ", "")}
                  </h3>
                );
              }
              if (line.startsWith("- ")) {
                return (
                  <li key={idx} className="ml-4 list-disc text-muted-foreground">
                    {line.replace("- ", "")}
                  </li>
                );
              }
              if (!line.trim()) return null;
              return (
                <p key={idx} className="text-foreground/90">
                  {line}
                </p>
              );
            })}
          </div>
        </div>
      ) : (
        !isGenerating && (
          <div className="text-center py-10 px-4 border border-dashed border-border/60 rounded-xl bg-secondary/10 space-y-2">
            <Brain className="size-10 text-muted-foreground/40 mx-auto" />
            <h3 className="text-sm font-semibold text-foreground">No Weekly CBT Report Generated Yet</h3>
            <p className="text-xs text-muted-foreground max-w-md mx-auto">
              Click "Generate 7-Day CBT Analysis" above to trigger DeepSeek-R1 CoT reasoning over your nightly SQLite reflections.
            </p>
          </div>
        )
      )}
    </div>
  );
}
